# GolangCI-Lint配置 - S+代码质量

run:
  timeout: 5m
  modules-download-mode: readonly
  
linters:
  enable:
    # 基础检查
    - gofmt          # 代码格式
    - goimports      # import排序
    - govet          # Go官方检查
    - errcheck       # 错误检查
    - staticcheck    # 静态分析
    
    # 安全检查
    - gosec          # 安全漏洞
    - gas            # 安全审计
    
    # 代码质量
    - gocyclo        # 圈复杂度
    - dupl           # 重复代码
    - misspell       # 拼写错误
    - ineffassign    # 无效赋值
    - unused         # 未使用代码
    - deadcode       # 死代码
    
    # 性能优化
    - prealloc       # slice预分配
    - gocritic       # 性能建议
    
    # 最佳实践
    - gochecknoinits # 禁止init函数
    - gochecknoglobals # 禁止全局变量
    - godox          # TODO/FIXME检查
    
  disable:
    - typecheck      # 已由go build检查

linters-settings:
  gocyclo:
    min-complexity: 15  # 圈复杂度阈值
  
  dupl:
    threshold: 100  # 重复代码阈值
  
  govet:
    check-shadowing: true  # 检查变量遮蔽
  
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  gosec:
    severity: "low"
    confidence: "low"

issues:
  exclude-rules:
    # 排除测试文件的某些检查
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    
    # 排除generated代码
    - path: internal/model
      linters:
        - gochecknoglobals

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

