apiVersion: apps/v1
kind: Deployment
metadata:
  name: zhihang-messenger-backend
  namespace: zhihang-messenger
  labels:
    app: zhihang-messenger-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zhihang-messenger-backend
  template:
    metadata:
      labels:
        app: zhihang-messenger-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/zhihang-messenger/backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "zhihang_messenger"
        - name: DB_USER
          value: "zhihang_messenger"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: MINIO_ENDPOINT
          value: "minio-service:9000"
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: access-key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: secret-key
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume
        configMap:
          name: backend-config
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: zhihang-messenger
  labels:
    app: zhihang-messenger-backend
spec:
  selector:
    app: zhihang-messenger-backend
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: zhihang-messenger
data:
  config.yaml: |
    server:
      port: 8080
      host: "0.0.0.0"
    database:
      host: "mysql-service"
      port: 3306
      name: "zhihang_messenger"
      user: "zhihang_messenger"
    redis:
      host: "redis-service"
      port: 6379
    minio:
      endpoint: "minio-service:9000"
    monitoring:
      enabled: true
      port: 9090
